apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: tis-uat
data:
  nginx.conf: |
   user  nginx;
   worker_processes  4;
   
   error_log  /var/log/nginx/error.log warn;
   pid        /var/run/nginx.pid;
   
   
   events {
       worker_connections  1024;
   }
   
   
   http {
       include       /etc/nginx/mime.types;
       default_type  application/octet-stream;
   
       log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';
   
       access_log  /var/log/nginx/access.log  main;
       server_tokens off;
       sendfile        on;
       tcp_nopush     on;
       client_max_body_size 900M;
       keepalive_timeout  65;
       proxy_read_timeout 1800;
       proxy_max_temp_file_size 0;
       add_header X-XSS-Protection "1; mode=block";
       add_header X-Frame-Options SAMEORIGIN;
       add_header X-Content-Type-Options nosniff;
       gzip  on;
   
       include /etc/nginx/conf.d/*.conf;
   }
  

